### ISSUE TITLE
Remove / make conditional the dependency on Fable.Core ?

### ISSUE THREAD

**Issue by bartelink** [alfonsogarciacaro/UnitsOfMeasure.Extra#3]
I'm hoping to use this in a low-dependencies, non-Fable-related set of example for a library.

I'm wondering (why it's necessary and/or) whether you'd accept a PR to remove (and/or make conditional) the [dependency on Fable.Core](https://github.com/alfonsogarciacaro/UnitsOfMeasure.Extra/blob/1b2fa87f0c2be7a65bc68869db116c57ca619381/src/UnitsOfMeasure.Extra.fsproj#L16)  ?

**Comment by alfonsogarciacaro** [comment]
Ups, the Fable.Core dependency shouldn't be needed at all! I think I copied the .fsproj from another project and forgot to remove it 😅 Thanks for pointing it out!

**Comment by bartelink** [comment]
No problem - thanks!
